server:
  applicationConnectors:
    - type: http
      port: 4080
  adminConnectors:
    - type: http
      port: 4081

redis:
  type: basic
  name: temperature-converter
  node:
    type: redis
    node: "redis:6379"
  redisCodec:
    type: string
  clientResources:
    type: default
    commandLatencyCollector:
      type: default
      enabled: false

version: 0.0.1
